AWSTemplateFormatVersion: 2010-09-09
Description: SAM Template containing infra for my "misc" repo

Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsitype
          AttributeType: S
        - AttributeName: gsitypesk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi2pk
          AttributeType: S
        - AttributeName: gsi3pk
          AttributeType: S
        - AttributeName: gsi3sk
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: gsitype
          KeySchema:
            - AttributeName: gsitype
              KeyType: HASH
            - AttributeName: gsitypesk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gsi2
          KeySchema:
            - AttributeName: gsi2pk
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gsi3
          KeySchema:
            - AttributeName: gsi3pk
              KeyType: HASH
            - AttributeName: gsi3sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
  PublicS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  PrivateS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  StreamlitAppUser:
    Type: "AWS::IAM::User"
    Properties:
      Path: /bot/
      UserName: !Ref AWS::StackName

  StreamlitAppUserCredentials:
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: !Ref StreamlitAppUser


  StreamlitAppUserCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString: !Sub '{"ACCESS_KEY":"${StreamlitAppUserCredentials}","SECRET_KEY":"${StreamlitAppUserCredentials.SecretAccessKey}"}'


  StreamlitAppUserPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "StreamlitAppUserPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
              - "s3:PutObject"
            Resource:
              - !Sub arn:aws:s3:::${PublicS3Bucket}
              - !Sub arn:aws:s3:::${PublicS3Bucket}/*
              - !Sub arn:aws:s3:::${PrivateS3Bucket}
              - !Sub arn:aws:s3:::${PrivateS3Bucket}/*
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource:
              - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoTable}'
              - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoTable}/index/*'
      Users:
        - !Ref StreamlitAppUser
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - PublicS3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  PublicS3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - PublicS3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content

  DynamoDBTableName:
    Value: !Ref DynamoTable
    Description: Name of the DynamoDB table

  PublicS3BucketName:
    Value: !Ref PublicS3Bucket
    Description: Name of the S3 bucket

  AppSecret:
    Value: !Ref StreamlitAppUserCredentialsSecret
    Description: App Secret
